### PR TITLE
Add `hreflang` Tags

### LINKED ISSUE #16: Add `hreflang` HTML Tags for Translated Pages
As the title says.

### TODO:

- [x] Add `hreflang` for site pages
- [x] Add `hreflang` for doc pages

### PR DESCRIPTION
**Pull request by ceolson01**
## Description

New Feature. This PR aims to add `hreflang` tags for versions of each page in alternate languages (when they exist). This also requires custom logic for docs pages.

## Changes

- Add `hreflang` tag to `SEO` component
- Add util which confirms each page exists
- Add custom logic for docs pages (since paths differ beyond just the locale)

## Demo

Here's how it behaves going from `es` locale, to `en` locale, showing how it handles no alternate versions as well (when an alternate version of a page doesn't exist - in this case a doc page).

hreflang tag

Closes #16

### CODE REVIEW

**Review by chmanie — COMMENTED** [review]
Wow, this is a lot to take in! I’m sure this is great, but it looks intimidating! Why is it so complex and when I fear that things might break more easily this way when making a tiny formatting mistake or having a bit of a different doc, is that rightfully so?

Can the big functions be split up into smaller, more easily digestible chunks?

**Review by rdig — COMMENTED** [review]
I did a first pass of this, but it's a lot to take in, and those two big functions don't make things easier either.

I'm going to let this sink in, then do another pass later.

**Review by rdig — APPROVED** [review]
This is all good, except for the `getAltLocaleVersions` method, which is really really hard to wrap your head around, especially if you are coming to this project fresh, w/o prior knowledge.

I've approved this, but try to take some time and find a better refactor for it. I've took a look at it, but the major problem is, that there's a lot of moving parts, and every code block does something different.

At the very least, just extract some of the code blocks in some helper methods. Even just that will be a step forward.

**Comment by ceolson01** [comment]
Outdated, antiquated, and unnecessary. Closing

**Pull request closed without merging**
